name: Build and Release EXE

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller src/main.py --onedir --windowed --noconfirm --distpath . --workpath .

      - name: Find EXE
        id: find-exe
        run: |
          echo "::set-output name=exe_path::$(Get-ChildItem -Path . -Filter main.exe -Recurse | Select-Object -ExpandProperty FullName)"

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ steps.find-exe.outputs.exe_path }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
