name: Build and Release EXE

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Check customtkinter Installation
        run: |
          pip show customtkinter

      - name: Build EXE
        run: |
          pyinstaller src/main.py --onedir --windowed --noconfirm --distpath ./dist --workpath ./build

      - name: Create ZIP Archive
        run: |
          powershell Compress-Archive -Path dist -DestinationPath dist.zip

      - name: Upload Dist ZIP to Release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
